// map common country/region names to flag emojis
const countryToFlag: Record<string, string> = {
	// specific countries
	'united states': '🇺🇸',
	canada: '🇨🇦',
	mexico: '🇲🇽',
	brazil: '🇧🇷',
	argentina: '🇦🇷',
	chile: '🇨🇱',
	colombia: '🇨🇴',
	peru: '🇵🇪',
	venezuela: '🇻🇪',
	ecuador: '🇪🇨',
	guatemala: '🇬🇹',
	cuba: '🇨🇺',
	bolivia: '🇧🇴',
	haiti: '🇭🇹',
	'dominican republic': '🇩🇴',
	honduras: '🇭🇳',
	paraguay: '🇵🇾',
	nicaragua: '🇳🇮',
	'el salvador': '🇸🇻',
	'costa rica': '🇨🇷',
	panama: '🇵🇦',
	uruguay: '🇺🇾',
	jamaica: '🇯🇲',
	'trinidad and tobago': '🇹🇹',
	guyana: '🇬🇾',
	suriname: '🇸🇷',
	belize: '🇧🇿',
	bahamas: '🇧🇸',
	barbados: '🇧🇧',
	'united kingdom': '🇬🇧',
	germany: '🇩🇪',
	france: '🇫🇷',
	italy: '🇮🇹',
	spain: '🇪🇸',
	netherlands: '🇳🇱',
	belgium: '🇧🇪',
	switzerland: '🇨🇭',
	austria: '🇦🇹',
	sweden: '🇸🇪',
	norway: '🇳🇴',
	denmark: '🇩🇰',
	finland: '🇫🇮',
	poland: '🇵🇱',
	'czech republic': '🇨🇿',
	hungary: '🇭🇺',
	romania: '🇷🇴',
	bulgaria: '🇧🇬',
	greece: '🇬🇷',
	portugal: '🇵🇹',
	ireland: '🇮🇪',
	croatia: '🇭🇷',
	serbia: '🇷🇸',
	slovenia: '🇸🇮',
	slovakia: '🇸🇰',
	estonia: '🇪🇪',
	latvia: '🇱🇻',
	lithuania: '🇱🇹',
	ukraine: '🇺🇦',
	russia: '🇷🇺',
	turkey: '🇹🇷',
	israel: '🇮🇱',
	'saudi arabia': '🇸🇦',
	'united arab emirates': '🇦🇪',
	qatar: '🇶🇦',
	kuwait: '🇰🇼',
	oman: '🇴🇲',
	bahrain: '🇧🇭',
	jordan: '🇯🇴',
	lebanon: '🇱🇧',
	egypt: '🇪🇬',
	morocco: '🇲🇦',
	algeria: '🇩🇿',
	tunisia: '🇹🇳',
	libya: '🇱🇾',
	sudan: '🇸🇩',
	ethiopia: '🇪🇹',
	kenya: '🇰🇪',
	uganda: '🇺🇬',
	tanzania: '🇹🇿',
	rwanda: '🇷🇼',
	ghana: '🇬🇭',
	nigeria: '🇳🇬',
	'south africa': '🇿🇦',
	india: '🇮🇳',
	pakistan: '🇵🇰',
	bangladesh: '🇧🇩',
	'sri lanka': '🇱🇰',
	nepal: '🇳🇵',
	china: '🇨🇳',
	japan: '🇯🇵',
	'south korea': '🇰🇷',
	'north korea': '🇰🇵',
	vietnam: '🇻🇳',
	thailand: '🇹🇭',
	malaysia: '🇲🇾',
	singapore: '🇸🇬',
	indonesia: '🇮🇩',
	philippines: '🇵🇭',
	myanmar: '🇲🇲',
	cambodia: '🇰🇭',
	laos: '🇱🇦',
	mongolia: '🇲🇳',
	taiwan: '🇹🇼',
	'hong kong': '🇭🇰',
	australia: '🇦🇺',
	'new zealand': '🇳🇿',
	fiji: '🇫🇯',
	'papua new guinea': '🇵🇬',
	iran: '🇮🇷',
	iraq: '🇮🇶',
	afghanistan: '🇦🇫',
	kazakhstan: '🇰🇿',
	uzbekistan: '🇺🇿',
	azerbaijan: '🇦🇿',
	georgia: '🇬🇪',
	armenia: '🇦🇲',

	// regions (use generic globe/map emojis)
	'north america': '🌎',
	'south america': '🌎',
	'central america': '🌎',
	'latin america': '🌎',
	caribbean: '🌎',
	europe: '🌍',
	'eastern europe': '🌍',
	'western europe': '🌍',
	'northern europe': '🌍',
	'southern europe': '🌍',
	'middle east': '🌍',
	africa: '🌍',
	'north africa': '🌍',
	'sub-saharan africa': '🌍',
	'east africa': '🌍',
	'west africa': '🌍',
	'central africa': '🌍',
	'southern africa': '🌍',
	asia: '🌏',
	'east asia': '🌏',
	'south asia': '🌏',
	'southeast asia': '🌏',
	'central asia': '🌏',
	'east asia & pacific': '🌏',
	oceania: '🌏',
	pacific: '🌏'
}

export function getCountryFlag(country: string): string {
	const normalized = country.toLowerCase().trim()
	return countryToFlag[normalized] || '🌐'
}
